CC=gcc

CFLAGS=-Wall -g
LIB=libhashtable
BINS=$(LIB).so $(LIB).a test test2

all: $(BINS)

%: %.c $(LIB).a
	$(CC) $(CFLAGS) $< -o $@ $(LIB).a

%.o: %.c
	$(CC) $(CFLAGS) -c $<

lib%.a: %.o
	ar -cvrs $@ $<

lib%.so: %.c
	$(CC) $(CFLAGS) -shared -fPIC $< -o $@

clean:
	rm -rf *.so *.a $(BINS)
