abc = "Hello world"
length = len(abc)
new = abc.lower()
r = abc.replace("world", "World!")
occurance = abc.count("o")
index = abc.find("w")
sp = abc.split(' ')
print(sp)
print("index", index)
print("occurance of o:", occurance)
print(length)
print(new)
print(r)
print(abc)
